# Generated by Django 4.2 on 2023-04-27 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_of_equipment', models.CharField(max_length=100, verbose_name='Марка технического средства')),
                ('garage_number', models.CharField(max_length=100, verbose_name='Гаражный(гос.) номер')),
                ('body_number', models.CharField(max_length=100, verbose_name='Номер кузова')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО водителя')),
                ('speedometer_reading', models.PositiveIntegerField(verbose_name='Показания спидометра')),
                ('fuel_brand', models.CharField(max_length=100, verbose_name='Марка топлива')),
                ('remaining_fuel', models.PositiveIntegerField(verbose_name='Остаток топлива')),
            ],
            options={
                'verbose_name': 'Информация о водителе',
                'verbose_name_plural': 'Информация о водителе',
            },
        ),
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_numder', models.CharField(max_length=15, verbose_name='Номер машины')),
                ('car_model', models.CharField(max_length=15, verbose_name='Модель машины')),
                ('waybill_number', models.PositiveIntegerField(verbose_name='Номер путевого листа')),
                ('deliver_full_name', models.CharField(max_length=150, verbose_name='ФИО водителя')),
                ('deliver_number', models.PositiveIntegerField(verbose_name='Табельный номер водителя')),
                ('is_recept', models.BooleanField(default=True, verbose_name='Статус получения')),
            ],
            options={
                'verbose_name': 'Детальная информация',
                'verbose_name_plural': 'Детальная информация',
            },
        ),
        migrations.CreateModel(
            name='IssuanceAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('issue_code', models.CharField(max_length=100, verbose_name='Код выдачи')),
                ('brand_code', models.CharField(max_length=100, verbose_name='Код марки')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('organization_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.detailinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выдача материалов',
                'verbose_name_plural': 'Выдача материалов',
            },
        ),
        migrations.CreateModel(
            name='CostAccountingBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.deliverdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сальдо по учету расходов',
                'verbose_name_plural': 'Сальдо по учету расходов',
            },
        ),
    ]
