# Generated by Django 4.2 on 2023-04-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailinfo',
            name='issued_by',
            field=models.PositiveIntegerField(default=0, verbose_name='Сколько выдано'),
        ),
    ]
