# Generated by Django 4.2 on 2023-04-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_detailinfo_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuanceaccounting',
            name='details',
        ),
        migrations.AddField(
            model_name='detailinfo',
            name='issuance_accounting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.issuanceaccounting', verbose_name='Выдача ГСМ'),
        ),
    ]
