# Generated by Django 4.1.5 on 2023-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_commision'),
    ]

    operations = [
        migrations.AddField(
            model_name='costaccountingbalances',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время выдачи'),
        ),
    ]
